name: Deploy Production Site (manual)
on:
  workflow_dispatch: {}

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to deployment branch (production)
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: deployment
          folder: .
          clean: true
          token: ${{ secrets.GITHUB_TOKEN }}
